# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# This is used to exclude rules from the convert
data exclusionRuleList
{
    ConvertFrom-StringData -StringData @'
        V-73523 = ''
        V-6599 = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6600 = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6601 = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6602 = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6604 = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6611 = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6612 = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6614 = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6615 = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6616 = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6617 = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6618 = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6620 = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6625 = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6627 = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-14657 = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-14658 = 'McAfee: Not Applicable to 64-bit systems.'
        V-14659 = 'McAfee: Not Applicable to 64-bit systems.'
        V-14660 = 'McAfee: Not Applicable to 64-bit systems.'
        V-14661 = 'McAfee: Not Applicable to 64-bit systems.'
        V-42563 = 'McAfee:exclusions have been documented with, and approved by, the ISSO/ISSM/DAA'
        V-42564 = 'McAfee:exclusions have been documented with, and approved by, the ISSO/ISSM/DAA'
        V-42565 = 'McAfee:with the assistance of the System Administrator, review each GUID key's szTaskName'
        V-42566 = 'McAfee:with the assistance of the System Administrator, review each GUID key's szTaskName'
        V-42567 = 'McAfee:with the assistance of the System Administrator, review each GUID key's szTaskName'
        V-42572 = 'McAfee:If the ExcludedURLs REG_MULTI_SZ has any entries, and the excluded URLs have not been documented with, and approved by, the ISSO/ISSM/DAA'
        V-14654 = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-94509 = 'Vsphere: To Be added in a future release'
        V-94025 = 'Vsphere: To Be added in a future release'
        V-94533 = 'Vsphere: To Be added in a future release'
        V-77189 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77191 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77195 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77201 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77205 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77209 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77213 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77217 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77221 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77223 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77227 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77231 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77233 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77235 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77239 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77243 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77247 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77249 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77255 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77259 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77263 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77267 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
        V-77269 = 'Set-ProcessMitigation doesn't allow for configuration of Override Settings, this will be updated in next release'
'@
}
